version: '3'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:5000:3000'
    environment:
      - REACT_APP_SERVER_URL=https://woc.scrypt.io/api

  express-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:5001:8001'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/woc
      - URL_PREFIX=/api
      - SERVER_PORT=8001
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/woc-plugin/api-data:/tmp # TODO: Make tmpfs, but need lots more RAM for that
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: woc
    volumes:
      - /opt/woc-plugin/db-data:/var/lib/postgresql/data

